name: Günlük Veri Güncelleme

on:
  schedule:
    - cron: '0 2 * * *'  # Her gün saat 02:00'de UTC (Türkiye saatiyle 05:00 civarı)
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Repo'yu klonla
        uses: actions/checkout@v3

      - name: Python ortamını kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Gerekli paketleri yükle
        run: pip install requests beautifulsoup4

      - name: Scraper'ı çalıştır
        run: python scraper.py

      - name: Değişiklikleri commit et
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data.json
          git commit -m "Veriler otomatik güncellendi" || echo "Değişiklik yok"
          git push
